import { createFileRoute } from "@tanstack/react-router";
import { Reveal } from "@/components/reveal";

export const Route = createFileRoute("/privacy-web")({
  head: () => ({
    meta: [
      { title: "Website Privacy Policy — Chimera Wallet" },
      { name: "description", content: "Chimera Website Privacy Policy. How we handle your data on chimerawallet.com." },
      { property: "og:title", content: "Website Privacy Policy — Chimera Wallet" },
      { property: "og:description", content: "Chimera Website Privacy Policy. How we handle your data on chimerawallet.com." },
    ],
  }),
  component: WebPrivacyPolicy,
});

function H2({ children }: { children: React.ReactNode }) {
  return <Reveal><h2 className="display mt-12 text-2xl md:text-3xl text-[var(--brand-green)]">{children}</h2></Reveal>;
}
function H3({ children }: { children: React.ReactNode }) {
  return <Reveal><h3 className="mt-8 text-lg md:text-xl font-semibold text-foreground">{children}</h3></Reveal>;
}
function P({ children }: { children: React.ReactNode }) {
  return <Reveal><p className="mt-4 text-sm md:text-base text-foreground/85 leading-relaxed">{children}</p></Reveal>;
}

function WebPrivacyPolicy() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16 md:py-24">
      <Reveal delay={120}><h1 className="hero-title">Chimera Website Privacy Policy</h1></Reveal>
      <Reveal delay={240}><p className="mt-4 text-xs text-muted-foreground">Last updated: June 09, 2025</p></Reveal>

      <P>
        Our Privacy Policy outlines our practices regarding the collection, usage, and disclosure of your information when you utilize our service. It also informs you about your privacy rights and legal protections. We utilize your personal data to enhance and deliver our service. By using our service, you consent to the collection and utilization of information as outlined in this Privacy Policy.
      </P>

      <H2>Interpretation and Definitions</H2>

      <H3>Interpretation</H3>
      <P>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
      </P>

      <H3>Definitions</H3>
      <P>For the purposes of this Privacy Policy:</P>
      <ul className="mt-4 list-disc space-y-3 pl-6 text-sm md:text-base text-foreground/85 leading-relaxed">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Company</strong> (referred to as either "the Company", Agreement) refers to Chimerawallet.io. "We", "Us" or "Our" in this Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Chimerawallet.io services and chimerawallet.com web site.</li>
        <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analysing how the Service is used.</li>
        <li><strong>Third-party Social Media Service</strong> refers to any website or any social network website through which a User can log in or create an account to use the Service.</li>
        <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
        <li><strong>Website</strong> refers to the Chimerawallet Website, accessible from https://chimerawallet.com</li>
        <li><strong>You</strong> mean the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>

      <H2>Collecting and Using Your Personal Data</H2>

      <H3>Types of Data Collected</H3>

      <H3>Personal Data</H3>
      <P>
        Chimera Wallet integrates with various third-party services through their APIs to enhance functionality. Only when using those third-party services through their APIs, third parties service providers may ask you to provides with certain personally identifiable information that can be used to contact or identify You. We do not collect or store user personal data. All data is transmitted directly to third-party service providers through our API integration. Our platform (Chimera) serves solely as an interface and does not retain copies of any user information or data processed through our system.
      </P>
      <P>
        While Chimera wallet itself maintains strict privacy standards and respects your absolute right to privacy and data sovereignty, we cannot guarantee the same level of privacy protection for data processed by third-party services when you choose to use their functionality through our app. We strongly encourage you to review all privacy policies of third-party services, conduct your own analysis, and choose carefully which services you wish to interact with through the Chimera wallet web site.
      </P>

      <H3>Usage Data</H3>
      <P>Usage Data is collected automatically when using the Service.</P>
      <P>
        Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
      </P>
      <P>
        When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
      </P>
      <P>
        We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
      </P>

      <H3>Tracking Technologies and Cookies</H3>
      <P>
        We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyse Our Service. The technologies We use may include:
      </P>
      <P>
        <strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
      </P>
      <P>
        <strong>Flash Cookies.</strong> Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies. For more information on how You can delete Flash Cookies, please read{" "}
        <a className="underline hover:text-[var(--brand-green)]" href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html" target="_blank" rel="noopener noreferrer">"Where can I change the settings for disabling, or deleting local shared objects?"</a>.
      </P>
      <P>
        <strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).
      </P>
      <P>
        Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. We use both Session and Persistent Cookies for the purposes set out below:
      </P>

      <H3>Necessary / Essential Cookies</H3>
      <P>Type: Session Cookies</P>
      <P>Administered by: Us</P>
      <P>
        Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
      </P>

      <H3>Cookies Policy / Notice Acceptance Cookies</H3>
      <P>Type: Persistent Cookies</P>
      <P>Administered by: Us</P>
      <P>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</P>

      <H3>Functionality Cookies</H3>
      <P>Type: Persistent Cookies</P>
      <P>Administered by: Us</P>
      <P>
        Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
      </P>
      <P>
        For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.
      </P>

      <H3>Use of Your Personal Data</H3>
      <P>The Company may use Personal Data for the following purposes:</P>
      <P>
        To provide and maintain our Service, including monitoring the usage of our Service. To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application's push notifications regarding updates or informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
      </P>
      <P>
        To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired about unless You have opted not to receive such information.
      </P>
      <P>
        To manage Your requests: To attend and manage Your requests to Us. For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and evaluating and improving our Service, products, services, marketing and your experience.
      </P>
      <P>We may share Your personal information in the following situations:</P>
      <ol className="mt-4 list-decimal space-y-3 pl-6 text-sm md:text-base text-foreground/85 leading-relaxed">
        <li><strong>With Service Providers:</strong> We may share Your personal information with Service Providers to monitor and analyse the use of our Service.</li>
        <li><strong>For business transfers:</strong> We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.</li>
        <li><strong>With Affiliates:</strong> We may share Your information with Our affiliates, in which case we will require those affiliates to honour this Privacy Policy. Affiliates include Our parent company and any other subsidiaries, joint venture partners or other companies that We control or that are under common control with Us.</li>
        <li><strong>With Your consent:</strong> We may disclose Your personal information for any other purpose with Your consent.</li>
      </ol>

      <H3>Retention of Your Personal Data</H3>
      <P>
        The company will only retain your Personal Data for as long as necessary for the purposes outlined in this Privacy Policy. We will retain and utilise your Personal Data to fulfil our legal obligations, resolve disputes, and enforce our agreements and policies.
      </P>
      <P>
        Additionally, the company will retain Usage Data for internal analysis purposes. Typically, Usage Data is retained for a shorter duration, unless it is utilised to enhance security, improve service functionality, or is legally required to be retained for longer periods.
      </P>

      <H3>Transfer of Your Personal Data</H3>
      <P>
        Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.
      </P>
      <P>
        Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
      </P>
      <P>
        The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organisation or a country unless there are adequate controls in place including the security of Your data and other personal information.
      </P>

      <H3>Disclosure of Your Personal Data</H3>

      <H3>Business Transactions</H3>
      <P>
        If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
      </P>
      <P>
        Law enforcement: Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).
      </P>

      <H3>Other Legal Requirements</H3>
      <P>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</P>
      <ol className="mt-4 list-decimal space-y-2 pl-6 text-sm md:text-base text-foreground/85 leading-relaxed">
        <li>Comply with a legal obligation</li>
        <li>Protect and defend the rights or property of the Company</li>
        <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
        <li>Protect the personal safety of Users of the Service or the public</li>
        <li>Protect against legal liability</li>
      </ol>

      <H3>Security of Your Personal Data</H3>
      <P>
        The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
      </P>

      <H2>Children's Privacy</H2>
      <P>
        Please note that Chimerawallet.io is not intended for use by nor directed at anyone under the age of 18 and we do not knowingly collect data relating to children. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers. If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.
      </P>

      <H2>Links to Other Websites</H2>
      <P>
        Our Service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third-party's site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third-party sites or services.
      </P>

      <H2>Your Rights</H2>
      <P>
        As a data subject, you have several rights related to your personal data. Below, we have described the various rights that you have as well as how you can exercise them.
      </P>

      <H3>Right of Access</H3>
      <P>
        You may, at any time, request access to the personal data that we hold which relates to you (you may have heard of this right being described as a "subject access request").
      </P>
      <P>
        Please note that this right entitles you to receive a copy of the personal data that we hold about you to enable you to check that it is correct and to ensure that we are processing that personal data lawfully. It is not a right that allows you to request personal data about other people, or a right to request specific documents from us that do not relate to your personal data. You can exercise this right at any time by writing to us (support@chimerawallet.com) and telling us that you are making a "subject access request". You do not have to fill in a specific form to make this kind of request.
      </P>

      <H3>Your Right to Rectification and Erasure</H3>
      <P>
        You may, at any time, request that we correct personal data that we hold about you that you believe is incorrect or inaccurate. Please note that we may ask you to verify any new data that you provide to us and may take our own steps to check that the new data you have supplied us with is right.
      </P>
      <P>
        You may also ask us to erase personal data that we control if you do not believe that we need to continue retaining it (you may have heard of this right described as the "right to be forgotten"). Although we will do everything to respect your request and personal data, it may not always be possible to erase all of your personal data as there may be legal requirements to keep certain personal data or technical limitations to the data we can delete. If erasure is not technically possible or we believe that we have a good legal reason to continue processing personal data that you ask us to erase, we will tell you this and our reasoning at the time we respond to your request.
      </P>
      <P>
        You can exercise this right at any time by writing to us (support@outlogi.net) and telling us that you are requesting to have your personal data rectified or erased and on what basis you are making that request. If you want us to replace inaccurate data with new data, you should tell us what that new data is. You do not have to fill in a specific form to make this kind of request.
      </P>

      <H3>Your Right to Restrict Processing</H3>
      <P>
        Where we process your personal data based on legitimate interest, you are entitled to ask us to stop processing it in that way if you feel that our continuing to do so impacts your fundamental rights and freedoms or if you feel that those legitimate interests are not valid. You may also ask us to stop processing your personal data (a) if you dispute the accuracy of that personal data and want us verify that data's accuracy; (b) where it has been established that our use of the data is unlawful but you do not want us to erase it; (c) where we no longer need to process your personal data (and would otherwise dispose of it) but you wish for us to continue storing it to enable you to establish, exercise or defend legal claims. You can exercise this right at any time by writing to us (info@chimerawallet.com) and telling us that you are requesting to have us stop processing the relevant aspect of your personal data and describing which of the above conditions you believe is relevant to that request. You do not have to fill in a specific form to make this kind of request.
      </P>

      <H3>Your Right to Object to Processing</H3>
      <P>
        You may object to the processing of your personal data where we rely on legitimate interest for processing that personal data. We will comply with your request unless we have a compelling overriding legitimate interest for processing or we need to continue processing your personal data to establish, exercise or defend a legal claim.
      </P>

      <H3>Your Right to Stop Receiving Communications</H3>
      <P>
        To unsubscribe from communications at any time, please click on the unsubscribe link at the bottom of any email and update your notification preferences in the App. For details on your rights to ask us to stop sending you various kinds of communications, please contact us (support@outlogic.net).
      </P>

      <H3>Withdrawal of Consent</H3>
      <P>
        Where we are relying on consent to process your personal data, you may withdraw consent at any time. However, this will not affect the lawfulness of any processing carried out before you withdraw your consent. If you withdraw your consent, we may not be able to provide certain products or services to you. We will advise you if this is the case at the time you withdraw your consent.
      </P>
      <P>
        Exercising your rights: When you write to us requesting to exercise your rights, we are entitled to ask you to prove that you are who you say you are. We may ask you to provide copies of relevant ID documents to help us verify your identity. It will help us to process your request if you clearly state which rights you wish to exercise and, where relevant, why it is that you are exercising them. The clearer and more specific you can be, the faster and more efficiently we can deal with your request. If you do not provide us with sufficient information, then we may delay actioning your request until you have provided us with additional information (and where this is the case, we will tell you).
      </P>

      <H2>Changes to this Privacy Policy</H2>
      <P>
        We may periodically update our Privacy Policy. Any changes will be communicated by posting the new Privacy Policy on this page.
      </P>
      <P>
        We'll notify you via email and/or through a prominent notice on our service before the changes take effect and update the "Last updated" date at the top of this Privacy Policy. It's advisable to review this Privacy Policy regularly for any updates. Changes are effective upon posting on this page. If you disagree with any modifications, please discontinue using Chimera Wallet Services. Your continued access and/or use of Chimerawallet.io Services and/or the Website will be considered as your acknowledgement and acceptance of the amendments to the revised Agreement.
      </P>

      <H2>Contact Us</H2>
      <P>
        If you have any questions about this Privacy Policy, You can contact us by email:{" "}
        <a className="underline hover:text-[var(--brand-green)]" href="mailto:info@chimerawallet.com">info@chimerawallet.com</a>
      </P>
    </main>
  );
}
